language: cpp
compiler:
 - gcc
os:
 - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    pcakges:
      - gcc-5
      - g++-5
      - clang-3.6

install:
# Upgrade GCC
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:george-edison55/precise-backports -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.9
  - sudo apt-get install -qq cmake
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
# Install conan
  - sudo pip install conan
script:
  - mkdir bin
  - cd bin
  - conan install .. --build=missing
  - cmake ..
  - make
